Search.appendIndex(
    [
                {
            "fqsen": "\\RAZDJELNIK_MAPE",
            "name": "RAZDJELNIK_MAPE",
            "summary": "\u0023\u0023\u0023\u0020Sistemska\u0020definicija\u0020za\u0020razdvajanje\u0020mapa\u0020u\u0020strukturi",
            "url": "namespaces/default.html#constant_RAZDJELNIK_MAPE"
        },                {
            "fqsen": "\\FIREHUB_ROOT",
            "name": "FIREHUB_ROOT",
            "summary": "\u0023\u0023\u0023\u0020Putanja\u0020do\u0020po\u010Detne\u0020mapa\u0020sustava",
            "url": "namespaces/default.html#constant_FIREHUB_ROOT"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Sustav",
            "name": "Sustav",
            "summary": "\u0023\u0023\u0023\u0020Osnovna\u0020klasa\u0020za\u0020pokretanje\u0020sustava",
            "url": "classes/FireHub-Jezgra-Sustav.html"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Sustav\u003A\u003Apokreni\u0028\u0029",
            "name": "pokreni",
            "summary": "\u0023\u0023\u0023\u0020Pokreni\u0020sustav",
            "url": "classes/FireHub-Jezgra-Sustav.html#method_pokreni"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Sustav\u003A\u003Aautoload\u0028\u0029",
            "name": "autoload",
            "summary": "\u0023\u0023\u0023\u0020U\u010Ditaj\u0020autoload\u0020datoteku",
            "url": "classes/FireHub-Jezgra-Sustav.html#method_autoload"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Sustav\u003A\u003Akernel\u0028\u0029",
            "name": "kernel",
            "summary": "\u0023\u0023\u0023\u0020Pokreni\u0020Kernel",
            "url": "classes/FireHub-Jezgra-Sustav.html#method_kernel"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Kernel",
            "name": "Kernel",
            "summary": "\u0023\u0023\u0023\u0020Osnovna\u0020klasa\u0020Kernel\u0020za\u0020pokretanje\u0020upita",
            "url": "classes/FireHub-Jezgra-Kernel.html"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Kernel\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "\u0023\u0023\u0023\u0020Konstruktor.",
            "url": "classes/FireHub-Jezgra-Kernel.html#method___construct"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Kernel\u003A\u003Apokreni\u0028\u0029",
            "name": "pokreni",
            "summary": "\u0023\u0023\u0023\u0020Pokreni\u0020Kernel",
            "url": "classes/FireHub-Jezgra-Kernel.html#method_pokreni"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\HTTP\\Kernel",
            "name": "Kernel",
            "summary": "\u0023\u0023\u0023\u0020Osnovna\u0020klasa\u0020Kernel\u0020za\u0020pokretanje\u0020HTTP\u0020upita",
            "url": "classes/FireHub-Jezgra-HTTP-Kernel.html"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\HTTP\\Kernel\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "\u0023\u0023\u0023\u0020Konstruktor.",
            "url": "classes/FireHub-Jezgra-HTTP-Kernel.html#method___construct"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\HTTP\\Kernel\u003A\u003Apokreni\u0028\u0029",
            "name": "pokreni",
            "summary": "\u0023\u0023\u0023\u0020Pokreni\u0020Kernel",
            "url": "classes/FireHub-Jezgra-HTTP-Kernel.html#method_pokreni"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\HTTP\\Kernel\u003A\u003Aodgovor\u0028\u0029",
            "name": "odgovor",
            "summary": "\u0023\u0023\u0023\u0020HTTP\u0020odgovor.",
            "url": "classes/FireHub-Jezgra-HTTP-Kernel.html#method_odgovor"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\HTTP\\Kernel\u003A\u003A\u0024zahtjev",
            "name": "zahtjev",
            "summary": "",
            "url": "classes/FireHub-Jezgra-HTTP-Kernel.html#property_zahtjev"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Konzola\\Kernel",
            "name": "Kernel",
            "summary": "\u0023\u0023\u0023\u0020Osnovna\u0020klasa\u0020Kernel\u0020za\u0020upita\u0020konzole",
            "url": "classes/FireHub-Jezgra-Konzola-Kernel.html"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Konzola\\Kernel\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "\u0023\u0023\u0023\u0020Konstruktor.",
            "url": "classes/FireHub-Jezgra-Konzola-Kernel.html#method___construct"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Konzola\\Kernel\u003A\u003Apokreni\u0028\u0029",
            "name": "pokreni",
            "summary": "\u0023\u0023\u0023\u0020Pokreni\u0020Kernel",
            "url": "classes/FireHub-Jezgra-Konzola-Kernel.html#method_pokreni"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Konzola\\Kernel\u003A\u003Aodgovor\u0028\u0029",
            "name": "odgovor",
            "summary": "\u0023\u0023\u0023\u0020Konzola\u0020odgovor.",
            "url": "classes/FireHub-Jezgra-Konzola-Kernel.html#method_odgovor"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Konzola\\Kernel\u003A\u003A\u0024zahtjev",
            "name": "zahtjev",
            "summary": "",
            "url": "classes/FireHub-Jezgra-Konzola-Kernel.html#property_zahtjev"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\HTTP\\Zahtjev",
            "name": "Zahtjev",
            "summary": "\u0023\u0023\u0023\u0020HTTP\u0020zahtjev",
            "url": "classes/FireHub-Jezgra-HTTP-Zahtjev.html"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\HTTP\\Zahtjev\u003A\u003Aurl\u0028\u0029",
            "name": "url",
            "summary": "\u0023\u0023\u0023\u0020Trenutni\u0020URL",
            "url": "classes/FireHub-Jezgra-HTTP-Zahtjev.html#method_url"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\HTTP\\Zahtjev\u003A\u003AurlKomponente\u0028\u0029",
            "name": "urlKomponente",
            "summary": "\u0023\u0023\u0023\u0020Razbijanje\u0020URL\u002Da\u0020u\u0020niz\u0020odvojen\u0020karakterom\u0020\u007B\/\u007D",
            "url": "classes/FireHub-Jezgra-HTTP-Zahtjev.html#method_urlKomponente"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\HTTP\\Zahtjev\u003A\u003Ametoda\u0028\u0029",
            "name": "metoda",
            "summary": "\u0023\u0023\u0023\u0020Dohvati\u0020HTTP\u0020metodu\u0020zahtjeva",
            "url": "classes/FireHub-Jezgra-HTTP-Zahtjev.html#method_metoda"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Test\\Sustav_Test",
            "name": "Sustav_Test",
            "summary": "\u0023\u0023\u0023\u0020Klasa\u0020za\u0020testiranje\u0020pokretanja\u0020sustava",
            "url": "classes/FireHub-Jezgra-Test-Sustav-Test.html"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Test\\Sustav_Test\u003A\u003ASetUp\u0028\u0029",
            "name": "SetUp",
            "summary": "",
            "url": "classes/FireHub-Jezgra-Test-Sustav-Test.html#method_SetUp"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Test\\Sustav_Test\u003A\u003AtestPokreniSustav\u0028\u0029",
            "name": "testPokreniSustav",
            "summary": "\u0023\u0023\u0023\u0020Test\u0020postavljanja\u0020status\u0020koda\u0020HTTP\u0020odgovora",
            "url": "classes/FireHub-Jezgra-Test-Sustav-Test.html#method_testPokreniSustav"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Test\\Sustav_Test\u003A\u003A\u0024sustav",
            "name": "sustav",
            "summary": "\u0023\u0023\u0023\u0020Sustav",
            "url": "classes/FireHub-Jezgra-Test-Sustav-Test.html#property_sustav"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Test\\Sustav_Test\u003A\u003A\u0024kernel",
            "name": "kernel",
            "summary": "Kernel",
            "url": "classes/FireHub-Jezgra-Test-Sustav-Test.html#property_kernel"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Konzola\\Zahtjev",
            "name": "Zahtjev",
            "summary": "\u0023\u0023\u0023\u0020Konzola\u0020zahtjev",
            "url": "classes/FireHub-Jezgra-Konzola-Zahtjev.html"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Odgovor",
            "name": "Odgovor",
            "summary": "\u0023\u0023\u0023\u0020Odgovor",
            "url": "classes/FireHub-Jezgra-Odgovor.html"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Odgovor\u003A\u003Asadrzaj\u0028\u0029",
            "name": "sadrzaj",
            "summary": "\u0023\u0023\u0023\u0020Sadr\u017Eaj\u0020odgovora",
            "url": "classes/FireHub-Jezgra-Odgovor.html#method_sadrzaj"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Zahtjev",
            "name": "Zahtjev",
            "summary": "\u0023\u0023\u0023\u0020Zahtjev",
            "url": "classes/FireHub-Jezgra-Zahtjev.html"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Konzola\\Odgovor",
            "name": "Odgovor",
            "summary": "\u0023\u0023\u0023\u0020Konzola\u0020odgovor",
            "url": "classes/FireHub-Jezgra-Konzola-Odgovor.html"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Konzola\\Odgovor\u003A\u003Asadrzaj\u0028\u0029",
            "name": "sadrzaj",
            "summary": "\u0023\u0023\u0023\u0020Sadr\u017Eaj\u0020odgovora",
            "url": "classes/FireHub-Jezgra-Konzola-Odgovor.html#method_sadrzaj"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Greske\\Greska",
            "name": "Greska",
            "summary": "\u0023\u0023\u0023\u0020Klasa\u0020za\u0020slanje\u0020gre\u0161aka",
            "url": "classes/FireHub-Jezgra-Greske-Greska.html"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\HTTP\\Greske\\Odgovor_Greska",
            "name": "Odgovor_Greska",
            "summary": "\u0023\u0023\u0023\u0020HTTP\u0020odgovor\u0020gre\u0161ke",
            "url": "classes/FireHub-Jezgra-HTTP-Greske-Odgovor-Greska.html"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Atributi\\Atribut",
            "name": "Atribut",
            "summary": "\u0023\u0023\u0023\u0020Interface\u0020za\u0020sve\u0020atribute",
            "url": "classes/FireHub-Jezgra-Atributi-Atribut.html"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Atributi\\Atribut\u003A\u003Aobradi\u0028\u0029",
            "name": "obradi",
            "summary": "\u0023\u0023\u0023\u0020Obradi\u0020atribut",
            "url": "classes/FireHub-Jezgra-Atributi-Atribut.html#method_obradi"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Komponente\\Servis_Interface",
            "name": "Servis_Interface",
            "summary": "\u0023\u0023\u0023\u0020Osnovni\u0020interface\u0020za\u0020sve\u0020servise",
            "url": "classes/FireHub-Jezgra-Komponente-Servis-Interface.html"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Komponente\\Servis_Kontejner",
            "name": "Servis_Kontejner",
            "summary": "\u0023\u0023\u0023\u0020Upravljanje\u0020ovisnostima\u0020definicija\u0020i\u0020dependency\u0020injection\u0020za\u0020servise",
            "url": "classes/FireHub-Jezgra-Komponente-Servis-Kontejner.html"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Komponente\\Servis_Kontejner\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "\u0023\u0023\u0023\u0020Konstruktor",
            "url": "classes/FireHub-Jezgra-Komponente-Servis-Kontejner.html#method___construct"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Komponente\\Servis_Kontejner\u003A\u003Aparameteri\u0028\u0029",
            "name": "parameteri",
            "summary": "\u007B\u0040inheritDoc\u007D",
            "url": "classes/FireHub-Jezgra-Komponente-Servis-Kontejner.html#method_parameteri"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Komponente\\Servis_Kontejner\u003A\u003Aservis\u0028\u0029",
            "name": "servis",
            "summary": "\u0023\u0023\u0023\u0020FQN\u0020naziv\u0020trenutog\u0020servisa",
            "url": "classes/FireHub-Jezgra-Komponente-Servis-Kontejner.html#method_servis"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Komponente\\Servis_Kontejner\u003A\u003AzadaniServis\u0028\u0029",
            "name": "zadaniServis",
            "summary": "\u0023\u0023\u0023\u0020Pro\u010Ditaj\u0020zadani\u0020servis\u0020iz\u0020konfiguracije\u0020servisa",
            "url": "classes/FireHub-Jezgra-Komponente-Servis-Kontejner.html#method_zadaniServis"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Komponente\\Servis_Kontejner\u003A\u003APOSLUZITELJI",
            "name": "POSLUZITELJI",
            "summary": "Putanja\u0020do\u0020konfiguracijske\u0020datoteke\u0020posluzitelja",
            "url": "classes/FireHub-Jezgra-Komponente-Servis-Kontejner.html#constant_POSLUZITELJI"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Komponente\\Servis_Kontejner\u003A\u003A\u0024posluzitelji",
            "name": "posluzitelji",
            "summary": "\u0023\u0023\u0023\u0020Lista\u0020posluzitelja",
            "url": "classes/FireHub-Jezgra-Komponente-Servis-Kontejner.html#property_posluzitelji"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Komponente\\Servis_Kontejner\u003A\u003A\u0024posluzitelj",
            "name": "posluzitelj",
            "summary": "",
            "url": "classes/FireHub-Jezgra-Komponente-Servis-Kontejner.html#property_posluzitelj"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Kontejner\\Greske\\Servis_Kontejner_Greska",
            "name": "Servis_Kontejner_Greska",
            "summary": "\u0023\u0023\u0023\u0020Servis\u0020Kontejner\u0020gre\u0161ke",
            "url": "classes/FireHub-Jezgra-Kontejner-Greske-Servis-Kontejner-Greska.html"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Kontejner\\Greske\\Servis_Posluzitelj_Greska",
            "name": "Servis_Posluzitelj_Greska",
            "summary": "\u0023\u0023\u0023\u0020Servis\u0020Poslu\u017Eitelj\u0020gre\u0161ke",
            "url": "classes/FireHub-Jezgra-Kontejner-Greske-Servis-Posluzitelj-Greska.html"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Kontejner\\Greske\\Kontejner_Greska",
            "name": "Kontejner_Greska",
            "summary": "\u0023\u0023\u0023\u0020Kontejner\u0020gre\u0161ke",
            "url": "classes/FireHub-Jezgra-Kontejner-Greske-Kontejner-Greska.html"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Komponente\\Test\\Test_Interface",
            "name": "Test_Interface",
            "summary": "\u0023\u0023\u0023\u0020Interface\u0020za\u0020testiranje",
            "url": "classes/FireHub-Jezgra-Komponente-Test-Test-Interface.html"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Komponente\\Test\\Test",
            "name": "Test",
            "summary": "\u0023\u0023\u0023\u0020Poslu\u017Eitelj\u0020za\u0020testiranje",
            "url": "classes/FireHub-Jezgra-Komponente-Test-Test.html"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Komponente\\Test\\Test\u003A\u003Anapravi\u0028\u0029",
            "name": "napravi",
            "summary": "",
            "url": "classes/FireHub-Jezgra-Komponente-Test-Test.html#method_napravi"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Komponente\\Test\\Test\u003A\u003A\u0024test_atribut",
            "name": "test_atribut",
            "summary": "",
            "url": "classes/FireHub-Jezgra-Komponente-Test-Test.html#property_test_atribut"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Komponente\\Test\\Test2",
            "name": "Test2",
            "summary": "\u0023\u0023\u0023\u0020Poslu\u017Eitelj\u0020za\u0020testiranje",
            "url": "classes/FireHub-Jezgra-Komponente-Test-Test2.html"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Komponente\\Test\\Test2\u003A\u003Anapravi\u0028\u0029",
            "name": "napravi",
            "summary": "",
            "url": "classes/FireHub-Jezgra-Komponente-Test-Test2.html#method_napravi"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Komponente\\Test\\Test2\u003A\u003A\u0024test_atribut",
            "name": "test_atribut",
            "summary": "",
            "url": "classes/FireHub-Jezgra-Komponente-Test-Test2.html#property_test_atribut"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Komponente\\Test\\Servisi\\Test_Servis",
            "name": "Test_Servis",
            "summary": "\u0023\u0023\u0023\u0020Servis\u0020za\u0020testiranje",
            "url": "classes/FireHub-Jezgra-Komponente-Test-Servisi-Test-Servis.html"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Komponente\\Test\\Servisi\\Test_Servis\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/FireHub-Jezgra-Komponente-Test-Servisi-Test-Servis.html#method___construct"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Komponente\\Test\\Servisi\\Test_Servis\u003A\u003A\u0024test",
            "name": "test",
            "summary": "",
            "url": "classes/FireHub-Jezgra-Komponente-Test-Servisi-Test-Servis.html#property_test"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Atributi",
            "name": "Atributi",
            "summary": "",
            "url": "namespaces/firehub-jezgra-atributi.html"
        },                {
            "fqsen": "\\FireHub\\Jezgra",
            "name": "Jezgra",
            "summary": "",
            "url": "namespaces/firehub-jezgra.html"
        },                {
            "fqsen": "\\FireHub",
            "name": "FireHub",
            "summary": "",
            "url": "namespaces/firehub.html"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Greske",
            "name": "Greske",
            "summary": "",
            "url": "namespaces/firehub-jezgra-greske.html"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\HTTP",
            "name": "HTTP",
            "summary": "",
            "url": "namespaces/firehub-jezgra-http.html"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\HTTP\\Greske",
            "name": "Greske",
            "summary": "",
            "url": "namespaces/firehub-jezgra-http-greske.html"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Komponente",
            "name": "Komponente",
            "summary": "",
            "url": "namespaces/firehub-jezgra-komponente.html"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Kontejner\\Greske",
            "name": "Greske",
            "summary": "",
            "url": "namespaces/firehub-jezgra-kontejner-greske.html"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Kontejner",
            "name": "Kontejner",
            "summary": "",
            "url": "namespaces/firehub-jezgra-kontejner.html"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Komponente\\Test",
            "name": "Test",
            "summary": "",
            "url": "namespaces/firehub-jezgra-komponente-test.html"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Komponente\\Test\\Servisi",
            "name": "Servisi",
            "summary": "",
            "url": "namespaces/firehub-jezgra-komponente-test-servisi.html"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Konzola",
            "name": "Konzola",
            "summary": "",
            "url": "namespaces/firehub-jezgra-konzola.html"
        },                {
            "fqsen": "\\FireHub\\Jezgra\\Test",
            "name": "Test",
            "summary": "",
            "url": "namespaces/firehub-jezgra-test.html"
        }            ]
);
